### ISSUE TITLE
TransactionContext Error using IPython-SQL

### ISSUE THREAD

**Issue by timrburnham** [Mause/duckdb_engine#129] opened 2021-08-15 23:54 UTC
I am hoping to use DuckDB in Jupyter Lab with the IPython-SQL extension for a nice little data science environment. It seems to throw an exception. Here's a simple test just using IPython:

```bash
$ pip install duckdb==0.2.8 duckdb-engine==0.1.7 ipython-sql==0.4.0
```

```python
Python 3.9.5 (default, May 11 2021, 08:20:37) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %load_ext sql

In [2]: %sql duckdb:////home/tim/test.db

In [3]: %sql select 42;
 * duckdb:////home/tim/test.db
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-661f615f78d4> in <module>
----> 1 get_ipython().run_line_magic('sql', 'select 42;')

~/Python/testcase/lib/python3.9/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2346                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2347             with self.builtin_trap:
-> 2348                 result = fn(*args, **kwargs)
   2349             return result
   2350 

~/Python/testcase/lib/python3.9/site-packages/decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

~/Python/testcase/lib/python3.9/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/Python/testcase/lib/python3.9/site-packages/decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

~/Python/testcase/lib/python3.9/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/Python/testcase/lib/python3.9/site-packages/sql/magic.py in execute(self, line, cell, local_ns)
    215 
    216         try:
--> 217             result = sql.run.run(conn, parsed["sql"], self, user_ns)
    218 
    219             if (

~/Python/testcase/lib/python3.9/site-packages/sql/run.py in run(conn, sql, config, user_namespace)
    366                 txt = sqlalchemy.sql.text(statement)
    367                 result = conn.session.execute(txt, user_namespace)
--> 368             _commit(conn=conn, config=config)
    369             if result and config.feedback:
    370                 print(interpret_rowcount(result.rowcount))

~/Python/testcase/lib/python3.9/site-packages/sql/run.py in _commit(conn, config)
    344     if _should_commit:
    345         try:
--> 346             conn.session.execute("commit")
    347         except sqlalchemy.exc.OperationalError:
    348             pass  # not all engines can commit

~/Python/testcase/lib/python3.9/site-packages/sqlalchemy/engine/base.py in execute(self, statement, *multiparams, **params)
   1246             )
   1247 
-> 1248             return self._exec_driver_sql(
   1249                 statement,
   1250                 multiparams,

~/Python/testcase/lib/python3.9/site-packages/sqlalchemy/engine/base.py in _exec_driver_sql(self, statement, multiparams, params, execution_options, future)
   1545 
   1546         dialect = self.dialect
-> 1547         ret = self._execute_context(
   1548             dialect,
   1549             dialect.execution_ctx_cls._init_statement,

~/Python/testcase/lib/python3.9/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1812 
   1813         except BaseException as e:
-> 1814             self._handle_dbapi_exception(
   1815                 e, statement, parameters, cursor, context
   1816             )

~/Python/testcase/lib/python3.9/site-packages/sqlalchemy/engine/base.py in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   1997                 )
   1998             else:
-> 1999                 util.raise_(exc_info[1], with_traceback=exc_info[2])
   2000 
   2001         finally:

~/Python/testcase/lib/python3.9/site-packages/sqlalchemy/util/compat.py in raise_(***failed resolving arguments***)
    205 
    206         try:
--> 207             raise exception
    208         finally:
    209             # credit to

~/Python/testcase/lib/python3.9/site-packages/sqlalchemy/engine/base.py in _execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1769                             break
   1770                 if not evt_handled:
-> 1771                     self.dialect.do_execute(
   1772                         cursor, statement, parameters, context
   1773                     )

~/Python/testcase/lib/python3.9/site-packages/duckdb_engine/__init__.py in do_execute(self, cursor, statement, parameters, context)
    129         context: PGExecutionContext,
    130     ) -> None:
--> 131         cursor.execute(statement, parameters, context)
    132 
    133     def do_executemany(

~/Python/testcase/lib/python3.9/site-packages/duckdb_engine/__init__.py in execute(self, statement, parameters, context)
     96                 raise NotImplementedError(*e.args) from e
     97             else:
---> 98                 raise e
     99 
    100 

~/Python/testcase/lib/python3.9/site-packages/duckdb_engine/__init__.py in execute(self, statement, parameters, context)
     91                 self.c.execute(statement)
     92             else:
---> 93                 self.c.execute(statement, parameters)
     94         except RuntimeError as e:
     95             if e.args[0].startswith("Not implemented Error"):

RuntimeError: TransactionContext Error: cannot commit - no transaction is active

```

**Comment by Mause** [comment] 2021-08-16 00:51
Thanks for raising this! I have a feeling it's caused by not setting up a default transaction when we connect to duckdb. I'll try to have a look at this today

**Comment by Mause** [comment] 2021-08-17 00:33
I've put out a rc release with a fix, let me know if you have any issues with it! https://pypi.org/project/duckdb-engine/0.1.8rc1/

**Comment by Alex-Monahan** [comment] 2021-08-17 01:02
Howdy!
Unfortunately I am still getting the same error as the person above with that release candidate. I tried a few things:
An in memory DuckDB (:memory:)
A file based DuckDB (That was new, not preexisting) The db does successfully get created in the file system.
Both %sql and %%sql (the multi-line version of the magic)

Anything other details I can provide?

Thanks,
Alex

`import duckdb
import pandas as pd
import sqlalchemy`
`%load_ext sql`
`%sql duckdb:///another_test_db.db`
`%sql select 42`

` * duckdb:///another_test_db.db
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-a17a5f51bcbe> in <module>
----> 1 get_ipython().run_line_magic('sql', 'select 42')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2285                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2286             with self.builtin_trap:
-> 2287                 result = fn(*args,**kwargs)
   2288             return result
   2289 

<decorator-gen-127> in execute(self, line, cell, local_ns)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

<decorator-gen-126> in execute(self, line, cell, local_ns)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

C:\ProgramData\Anaconda3\lib\site-packages\sql\magic.py in execute(self, line, cell, local_ns)
     93 
     94         try:
---> 95             result = sql.run.run(conn, parsed['sql'], self, user_ns)
     96 
     97             if result is not None and not isinstance(result, str) and self.column_local_vars:

C:\ProgramData\Anaconda3\lib\site-packages\sql\run.py in run(conn, sql, config, user_namespace)
    339                 txt = sqlalchemy.sql.text(statement)
    340                 result = conn.session.execute(txt, user_namespace)
--> 341             _commit(conn=conn, config=config)
    342             if result and config.feedback:
    343                 print(interpret_rowcount(result.rowcount))

C:\ProgramData\Anaconda3\lib\site-packages\sql\run.py in _commit(conn, config)
    318     if _should_commit:
    319         try:
--> 320             conn.session.execute('commit')
    321         except sqlalchemy.exc.OperationalError:
    322             pass  # not all engines can commit

C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py in execute(self, statement, *multiparams, **params)
   1251                 params,
   1252                 _EMPTY_EXECUTION_OPTS,
-> 1253                 future=False,
   1254             )
   1255 

C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py in _exec_driver_sql(self, statement, multiparams, params, execution_options, future)
   1552             execution_options,
   1553             statement,
-> 1554             distilled_parameters,
   1555         )
   1556 

C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py in _execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1813         except BaseException as e:
   1814             self._handle_dbapi_exception(
-> 1815                 e, statement, parameters, cursor, context
   1816             )
   1817 

C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py in _handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   1997                 )
   1998             else:
-> 1999                 util.raise_(exc_info[1], with_traceback=exc_info[2])
   2000 
   2001         finally:

C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py in raise_(***failed resolving arguments***)
    205 
    206         try:
--> 207             raise exception
    208         finally:
    209             # credit to

C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py in _execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1770                 if not evt_handled:
   1771                     self.dialect.do_execute(
-> 1772                         cursor, statement, parameters, context
   1773                     )
   1774 

C:\ProgramData\Anaconda3\lib\site-packages\duckdb_engine\__init__.py in do_execute(self, cursor, statement, parameters, context)
    109         context: PGExecutionContext,
    110     ) -> None:
--> 111         cursor.execute(statement, parameters, context)
    112 
    113     def do_executemany(

C:\ProgramData\Anaconda3\lib\site-packages\duckdb_engine\__init__.py in execute(self, statement, parameters, context)
     76                 raise NotImplementedError(*e.args) from e
     77             else:
---> 78                 raise e
     79 
     80 

C:\ProgramData\Anaconda3\lib\site-packages\duckdb_engine\__init__.py in execute(self, statement, parameters, context)
     71                 self.c.execute(statement)
     72             else:
---> 73                 self.c.execute(statement, parameters)
     74         except RuntimeError as e:
     75             if e.args[0].startswith("Not implemented Error"):

RuntimeError: TransactionContext Error: cannot commit - no transaction is active`

**Comment by timrburnham** [comment] 2021-08-17 02:09
Same result as Alex on Linux, Python 3.9.5. I finally had some luck when I commented out a few lines from the IPython-SQL extension, in sql/run.py:

```python
            _commit(conn=conn, config=config)
            if result and config.feedback:
                print(interpret_rowcount(result.rowcount))
```

By itself, the commit didn't work... maybe DuckDB needs to be on the _COMMIT_BLACKLIST_DIALECTS. The result.rowcount also didn't make any sense, so I killed that part too, and now I'm able to run typical SQL operations:

```python
In [3]: %sql select 42
 * duckdb:////home/tim/d.db
Out[3]: [(42,)]

In [4]: %sql CREATE TABLE items(item VARCHAR, value DECIMAL(10,2), count INTEGER)
 * duckdb:////home/tim/d.db
Out[4]: []

In [5]: %sql INSERT INTO items VALUES ('jeans', 20.0, 1), ('hammer', 42.2, 2)
 * duckdb:////home/tim/d.db
Out[5]: [(2,)]

In [6]: %sql SELECT * FROM items
 * duckdb:////home/tim/d.db
Out[6]: [('jeans', Decimal('20.00'), 1), ('hammer', Decimal('42.20'), 2)]

In [7]: %sql SELECT count(1) FROM items
 * duckdb:////home/tim/d.db
Out[7]: [(2,)]
```

**Comment by Mause** [comment] 2021-08-17 02:27
Can you both please confirm that you're using the 0.1.8rc1 release I put out earlier today?

**Comment by timrburnham** [comment] 2021-08-17 02:30
Can confirm:

```bash
$ pip list | grep duckdb
duckdb              0.2.8
duckdb-engine       0.1.8rc1
```

**Comment by Mause** [comment] 2021-08-17 02:48
@timrburnham thanks! I'll have a closer look this evening

**Comment by Alex-Monahan** [comment] 2021-08-17 14:32
Yes, I am on the release candidate as well. 
![image](https://user-images.githubusercontent.com/52226177/129744518-e499833d-64ab-4a48-ac79-d23482841c6d.png)

**Comment by Mause** [comment] 2021-08-18 07:06
Okay, trying this again - I've published `0.1.8-rc.3`, can you please see if that one works for you both?

I've included a very basic test here, if you'd like to add to it: https://github.com/Mause/duckdb_engine/blob/master/duckdb_engine/tests/test_basic.py#L142

**Comment by timrburnham** [comment] 2021-08-18 13:13
rc3 fixed it for me!

![image](https://user-images.githubusercontent.com/5595345/129904066-7d4e5f69-05c0-4744-9c93-457d49e7fe41.png)

Thanks so much!

**Comment by Mause** [comment] 2021-08-18 13:37
Awesome, thanks for testing it out! I'll close this issue now

**Closed by Mause** 2021-08-18 13:37 UTC
Labels: bug

**Comment by Alex-Monahan** [comment] 2021-08-18 13:59
Works for me too! Thank you again - this is awesome. I'm including it into my first ever blog post in the next few days (halfway done!). Happy to give you a shout out! :-)
